# Generated by Django 3.2.8 on 2022-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolcito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
